
set-option -g default-shell /usr/local/bin/fish
set -g default-command /usr/local/bin/fish

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind s split-window -h
bind v split-window -v

setw -g mouse on
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi Y send -X copy-line
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

set-option -g status-justify "centre"
set-option -g status-left-length 20
set-option -g status-right-length 60
set-option -g status-bg "colour238"
set-option -g status-fg "colour255"
set-option -g status-left-bg "colour255"
set-option -g status-left-fg "colour241"
set-option -g status-right-bg "colour255"
set-option -g status-right-fg "colour241"
set-option -g status-left "#[bold] Session: #S #[default]"
set-option -g status-right "#[bold] %m/%d %H:%M:%S#[default] "
set-window-option -g window-status-current-fg "colour255"
set-window-option -g window-status-current-bg "colour165"
set-window-option -g window-status-format " #I: #W "
set-window-option -g window-status-current-format "#[bold] #I: #W #[default]"
